config/routes.rb
Rails.application.routes.draw do
  root :to => 'skills#index'

  # get '/' => 'home#index'

  get "/log-in" => "sessions#new"
  post "/log-in" => "sessions#create"
  get "/log-out" => "sessions#destroy", as: :log_out

  resources :users do
    resources :posts
  end

  resources :posts do
    resources :comments
  end

  resources :users do
    resources :skills
  end

  resources :skills do
    resources :projects
  end

  resources :users do
    resources :references
  end

end

app/models/comment.rb
class Comment < ActiveRecord::Base
  belongs_to :post

  validates :title, :presence => true
  validates :body, :presence => true

end

app/models/post.rb
class Post <ActiveRecord::Base
  belongs_to :user

  validates :title, :presence => true
  validates :body, :presence => true

end

app/models/project.rb
class Project < ActiveRecord::Base
  belongs_to :skill

  validates :name, :presence => true
  validates :description, :presence => true
  validates :number, :presence => true
end

app/models/reference.rb
class Reference < ActiveRecord::Base
  belongs_to :user

  validates :name, :presence => true
  validates :phone, :presence => true
  validates :email, :presence => true
  validates :body, :presence => true
  
end

app/models/skill.rb
class Skill < ActiveRecord::Base
  belongs_to :user
  has_many :projects
  validates :name, :presence => true
  validates :description, :presence => true
  validates :number, :presence => true
end

app/models/user.rb
class User < ActiveRecord::Base
  has_many :posts
  has_many :skills
  has_many :references

  attr_accessor :password
  validates_confirmation_of :password
  before_save :encrypt_password

  def encrypt_password
    self.password_salt = BCrypt::Engine.generate_salt
    self.password_hash = BCrypt::Engine.hash_secret(password, password_salt)
  end

  def self.authenticate(username, password)
    user = User.where(username: username).first
    if user && user.password_hash == BCrypt::Engine.hash_secret(password, user.password_salt)
      user
    else
      nil
    end
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  def current_user
    @current_user ||= User.find(session[:user_id]) if session[:user_id]
    rescue ActiveRecord::RecordNotFound
  end

  helper_method :current_user
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController

  def new
    @post = Post.find(params[:post_id])
    @comment = Comment.new
  end

  def create
    @post = Post.find(params[:post_id])
    @user = User.find(@post.user_id)
    @comments = @post.comments
    @comment = @post.comments.new(comment_params)
    if @comment.save
      flash[:notice] = "Comment added to " + @post.title + "."

    else
      render :new
    end
    respond_to do |format|
      format.html { redirect_to user_post_path(@user, @post) }
      format.js
    end
  end

private
  def comment_params
    params.require(:comment).permit(:title, :body)
  end
end

app/controllers/home_controller.rb
class HomeController <ApplicationController

  def index
  end

end

app/controllers/posts_controller.rb
class PostsController < ApplicationController

  def index
    @posts = Post.all
    @user = User.find(params[:user_id])
  end

  def show
    @user = User.find(params[:user_id])
    @post = Post.find(params[:id])
    @comments = @post.comments
  end

  def new
    @user = current_user
    @post = Post.new
  end

  def create
    @user = current_user
    @post = @user.posts.new(post_params)
    if @post.save
      flash[:notice] = @post.title + ' has been added.'
      redirect_to user_posts_path
    else
      render :new
    end
  end

  def edit
    @user = User.find(params[:user_id])
    @post = Post.find(params[:id])
  end

  def update
    @user = User.find(params[:user_id])
    @post = Post.find(params[:id])
    if @post.update(post_params)
      flash[:notice] = @post.title + ' has been updated.'
      redirect_to user_post_path(@user, @post)
    else
      render :edit
    end
  end

  def destroy
    @user = User.find(params[:user_id])
    @post = Post.find(params[:id])
    @post.destroy
    flash[:notice] = @post.title + " successfully deleted!"

    redirect_to user_posts_path(@user, @post)
  end

private

  def post_params
    params.require(:post).permit(:title, :body)
  end

end

app/controllers/projects_controller.rb
class ProjectsController < ApplicationController
  def new
    @skill = Skill.find(params[:skill_id])
    @project = @skill.projects.new
  end

  def show
    @skill = Skill.find(params[:skill_id])
    @project = Project.find(params[:id])
  end

  def create
    @skill = Skill.find(params[:skill_id])
    @project = @skill.projects.new(project_params)
    if @project.save
      flash[:notice] = @project.name + " has been added to " + @skill.name + "!"
      redirect_to skill_path(@project.skill)
    else
      render :new
    end
  end

  def edit
    @skill = Skill.find(params[:skill_id])
    @project = Project.find(params[:id])
  end

  def update
    @skill = Skill.find(params[:skill_id])
    @project = Project.find(params[:id])
    if @project.update(project_params)
      flash[:notice] = @project.name + " has been edited!"
      redirect_to skill_project_path(@skill, @project)
    else
      render :edit
    end
  end

  def destroy
    @skill = Skill.find(params[:skill_id])
    @project = Project.find(params[:id])
    @project.destroy
    flash[:notice] = @project.name + " has been deleted!"
    redirect_to skill_path(@skill)
  end

private
  def project_params
    params.require(:project).permit(:name, :description, :number)
  end
end

app/controllers/references_controller.rb
class ReferencesController < ApplicationController

  def new
    @user = User.find(params[:user_id])
    @reference = @user.references.new
  end

  def create
    @user = User.find(params[:user_id])
    @reference = @user.references.new(reference_params)
    if @reference.save
      flash[:notice] = "Reference added."
    else
      render :new
    end
    respond_to do |format|
      format.html { redirect_to user_references_path(@user, @reference) }
      format.js
    end
  end

private
  def reference_params
    params.require(:reference).permit(:name, :phone, :email, :body)
  end

end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

  def new
  end

  def create
    @user = User.authenticate(params[:username], params[:password])
    if @user
      flash[:notice] = "Welcome " + @user.username + "!"
      session[:user_id] = @user.id
      redirect_to skills_path
    else
      flash[:alert] = "There was a problem logging you in."
      redirect_to log_in_path
    end
  end

  def destroy
    session[:user_id] = nil
    flash[:notice] = "You've been logged out successfully."
    redirect_to "/"
  end

end

app/controllers/skills_controller.rb
class SkillsController < ApplicationController
  def index
    @skills = Skill.all
    @user = current_user
    @references = Reference.all
  end

  def show
    @skill = Skill.find(params[:id])
  end

  def new
    @skill = Skill.new
  end

  def create
    @skill = Skill.new(skill_params)
    if @skill.save
      flash[:notice] = @skill.name + " successfully added!"
      redirect_to skills_path
    else
      render :new
    end
  end

  def edit
    @skill = Skill.find(params[:id])
  end

  def update
    @skill = Skill.find(params[:id])
    if @skill.update(skill_params)
      flash[:notice] = @skill.name + " successfully edited!"
      redirect_to skill_path
    else
      render :edit
    end
  end

  def destroy
    @skill = Skill.find(params[:id])
    @skill.destroy
    flash[:notice] = @skill.name + " successfully deleted!"
    redirect_to skills_path
  end

private
  def skill_params
    params.require(:skill).permit(:name, :description, :number)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      flash[:notice] = "Welcome " +  @user.username + "!"
      redirect_to '/'
    else
      flash[:alert] = 'There was a problem creating your account. Please try again.'
      redirect_to :back
    end
  end

  private
  def user_params
    params.require(:user).permit(:username, :email, :password, :password_confirmation)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/comments/_comment.html.erb
<li id="comment_<%= comment.id %>">
  <h3><%= comment.title %></h3>
  <p><%= comment.body %></p>
</li>

app/views/comments/_form.html.erb
<%= render 'layouts/errors', :object => @comment %>

<%= form_for [@post, @comment], remote: true do |f| %>
<%= f.label :title %>
<%= f.text_field :title %>
<%= f.label :body %>
<%= f.text_area :body %>
<%= f.submit :class => "btn btn-success" %>
<% end %>

app/views/comments/create.js.erb
$('#new_comment').remove();
$('#add_comment_link').show();
$('#comments_list').append('<%= j render(@comment) %>');

app/views/comments/new.js.erb
$('#add_comment_link').hide().after('<%= j render("form") %>');

app/views/home/index.html.erb
<h1>Welcome to Ian's Personal Portfolio Home Page</h1>
<h3>You must create an account and log in to experience the full functionality of this site.</h3>
<h5>If you are not logged in, you will still be able to view Skills and Projects, but you will be unable to view blog posts or leave your own comments.</h5>

<%= link_to 'View All of the things Ian has learned!', skills_path %>

<% if current_user != nil %>

<% end %>

app/views/layouts/_errors.html.erb
<% if object.errors.any? %>
  <h3>Please fix the following errors:</h3>
  <ul>
    <% object.errors.full_messages.each do |message| %>
      <li><%= message %></li>
    <% end %>
  </ul>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>PersonalPortfolio</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
  <script src='/assets/javascripts/scripts.js'></script>
</head>
<body>
  <nav class="navbar navbar-inverse navbar-fixed-top" id="my-navbar">
    <div class="container-fluid">
      <div class="navbar-header">
        <button type="button" class="navbar-toggle collapse" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
          <span class="sr-only">Toggle navigation</span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
        </button>

        <%= link_to "Ian's Personal Portfolio Home", "/", class: "navbar-brand"  %>
      </div>

      <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
        <ul class="nav navbar-nav navbar-left special-color">
          <% if current_user == nil %>
            <li><%= link_to 'You must log in to view all contents of the site.', log_in_path %></li>
          <% else %>
            <li><%= link_to "Logged in as: #{current_user.username}", '/'  %></li>
          <% end %>
        </ul>

        <ul class="nav navbar-nav navbar-right special-color">
          <% if current_user == nil %>
            <li><%= link_to 'Log In', log_in_path %></li>
            <li><%= link_to 'Register', new_user_path %></li>
          <% else %>
            <li><%= link_to "Log Out", log_out_path %></li>
          <% end %>
        </ul>
      </div>

    </div>
  </nav>

  <div class = "container">
    <%= flash[:notice] %>
    <%= flash[:alert] %>

    <%= yield %>
  </div>

</body>
</html>

app/views/posts/_form.html.erb
<%= render 'layouts/errors', :object => @post %>

<%= form_for [@user, @post] do |f| %>
  <%= f.label :title %>
  <%= f.text_field :title %>
  <%= f.label :body %>
  <%= f.text_area :body %>
  <%= f.submit "Add Post" %>
<% end %>

app/views/posts/edit.html.erb
<h1>Edit Post</h1>

<%= render 'form' %>

app/views/posts/index.html.erb
<h1>Ian's Blog Posts</h1>

<% if current_user != nil && current_user.admin %>
  <%= link_to "Add Post", new_user_post_path(@user), :class => "btn btn-success" %> <br/>
<% end %>

<% @posts.each do |post| %>
<h3><%= link_to post.title, user_post_path(@user, post) %></h3>
<h4><%= post.body %></h4>
<% end %>

app/views/posts/new.html.erb
<h1>New Post</h1>

<%= render 'form' %>

app/views/posts/show.html.erb
<h1><%= @post.title %></h1>
<h3><%= @post.body %></h3>

<% if current_user != nil && current_user.admin %>
  <%= link_to "Edit Post", edit_user_post_path(@user, @post) %>
  <%= link_to "Delete Post", user_post_path(@user, @post), data: {method: 'delete', confirm:'are you sure?'} %>
<% end %>

<%= link_to "Add Comment", new_post_comment_path(@post), id:"add_comment_link", remote: true %>

<br />

<ul id="comments_list">
  <%= render(@comments) %>
</ul>

app/views/projects/_form.html.erb
<%= render 'layouts/errors', :object => @project %>

<%= form_for [@skill, @project] do |f| %>
  <%= f.label :name %>
  <%= f.text_field :name %>
  <%= f.label :description %>
  <%= f.text_field :description %>
  <%= f.label :number %>
  <%= f.text_field :number %>
  <%= f.submit :class => "btn btn-success" %>
<% end %>

app/views/projects/edit.html.erb
<h1>Edit <%= @project.name %></h1>

<%= render 'form' %>

app/views/projects/new.html.erb
<h1>New project to add to <%= @skill.name %></h1>

<%= render 'form' %>

app/views/projects/show.html.erb
<div class= "container">
  <div class="intro">
    <h1><%= @project.name %></h1>
  </div>
  <div class="content">
    <h3><%= @project.description %></h3>
  </div>

  <% if current_user != nil && current_user.admin %>
    <div class="altering">
      <p><%= link_to "Edit " + @project.name, edit_skill_project_path, :class => "btn btn-primary" %>

      <%= link_to "Delete " + @project.name, skill_project_path(@skill, @project), :class => "btn btn-danger",
                                  :data =>{:confirm => "Are you sure you want to delete " + @project.name + " from " + @skill.name + "?",
                                    :method => 'delete'} %></p>
    </div>
  <% end %>

  <br>

  <p><%= link_to "Back to " + @skill.name + " page", skill_path, :class => "btn btn-default" %></p>
</div>

app/views/references/_form.html.erb
<%= render 'layouts/errors', :object => @reference %>

<%= form_for [@user, @reference], remote: true do |f| %>
  <%= f.label :name %>
  <%= f.text_field :name %>
  <%= f.label :email %>
  <%= f.text_field :email %>
  <%= f.label :phone %>
  <%= f.text_field :phone %>
  <%= f.label :body %>
  <%= f.text_area :body %>
  <%= f.submit :class => "btn btn-success" %>
<% end %>

app/views/references/_reference.html.erb
<p id="reference_<%= reference.id %>">
  <hr>
  <p>Name: <%= reference.name %></p>
  <p>Email: <%= reference.email %></p>
  <p>Phone: <%= reference.phone %></p>
  <p>Experience with Ian:</p>
  <p><%= reference.body %></p>
</p>

app/views/references/create.js.erb
$('#new_reference').remove();
$('#add_reference_link').show();
$('#references_list').append('<%= j render(@reference) %>');

app/views/references/new.js.erb
$('#add_reference_link').hide().after('<%= j render("form") %>');

app/views/skills/_form.html.erb
<%= render 'layouts/errors', :object => @skill %>

<%= form_for @skill do |f| %>
  <%= f.label :name %>
  <%= f.text_field :name %>
  <%= f.label :description %>
  <%= f.text_field :description %>
  <%= f.label :number %>
  <%= f.text_field :number %>
  <%= f.submit :class => "btn btn-success" %>
<% end %>

app/views/skills/edit.html.erb
<h1>Edit Skill</h1>

<%= render 'form' %>

app/views/skills/index.html.erb
<div class= "intro">
  <h1>Welcome to Ian Bevel's personal profile!</h1>
  <h4>Learn all about my journey into the exciting world of Programming!</h4>
</div>

<div class="row">
  <div class="col-md-6">
    <div class="divs">
      <h3>About Ian:</h3>
      <p>This is just filler text until I decide what is actually going to go in here.  I am thinking some basic bio stuff and maybe a link to my resume.</p>
    </div>
    <div class="divs">
      <h3>Contact Ian:</h3>
      <p>Email: ian.anthony.bevel@gmail.com</p>
      <p>Phone: (971) 404-8409</p>
    </div>
  </div>

  <div class="col-md-6 divs">
    <h1>Skills/Competencies</h1>
    <p>Click the link to view projects where I used the skill!</p>

    <ul>
      <% @skills.each do |skill| %>
      <li><h4><%= link_to skill.name, skill_path(skill) %></h4></li>
      <% end %>
    </ul>

    <% if current_user != nil && current_user.admin %>
    <%= link_to 'Add a Skill', new_skill_path, :class => "btn btn-success" %>
    <% end %>
  </div>
</div>

<% if current_user %>
  <div class="altering">
    <%= link_to 'View Posts', user_posts_path(@user, @posts), class: 'btn btn-success' %>
    <button name="see_references" class='btn btn-success' id="see_references" type="submit">See References</button>
    <button name="hide_references" class='btn btn-success' id="hide_references" type="submit">Hide References</button>

    <% if current_user.admin %>
      <%= link_to 'Add Reference', new_user_reference_path(@user, @reference), class: 'btn btn-success',id: 'add_reference_link', remote: true %>
    <% end %>
  </div>

  <ul id="references_list">
    <div class="divs">
      <%= render(@references) %>
    </div>
  <ul>

<% end %>

app/views/skills/new.html.erb
<h1>New Skill</h1>

<%= render 'form' %>

app/views/skills/show.html.erb
<div class="container">
  <div class= "intro">
    <h1><%= @skill.name %></h1>
  </div>

  <div class="container">
    <div class="col-md-8">
      <div class="content">
        <h3><%= @skill.description %></h3>
      </div>
    </div>

    <div class="col-md-4">
      <div class= "divs">
        <% if @skill.projects.any? %>
        <h4>Here are all the projects that demonstrate the use of <%= @skill.name %>:</h4>

          <ul>
            <% @skill.projects.each do |project| %>
              <li><%= link_to project.name, skill_project_path(@skill, project) %></li>
            <% end %>
          </ul>

        <% else %>
          <h4>There are no projects associated with <%= @skill.name %> yet. </h4>

        <% end %>
        <% if current_user != nil && current_user.admin %>
          <p><%= link_to "Add project to " + @skill.name, new_skill_project_path(@skill), :class => "btn btn-success" %></p>
        <% end %>
      </div>
    </div>
  </div>
  <% if current_user != nil && current_user.admin %>
    <div class= 'altering'>
        <p>
          <%= link_to "Edit " + @skill.name, edit_skill_path(@skill), :class => "btn btn-primary" %>

          <%= link_to "Delete " + @skill.name, skill_path(@skill), :class => "btn btn-danger",
                                    :data => {:confirm => "Are you sure you want to delete" + @skill.name + "?",
                                              :method => 'delete'} %>
        </p>

    </div>
  <% end %>
  <br>

  <p><%= link_to "Return to Skills", skills_path, :class => "btn btn-default" %></p>

</div>

app/views/users/_form.html.erb
<%= form_for User.new do |f| %>
  <%= f.label :username %>
  <%= f.text_field :username %>
  <%= f.label :email %>
  <%= f.text_field :email %>
  <%= f.label :password %>
  <%= f.password_field :password %>
  <%= f.label :password_confirmation %>
  <%= f.password_field :password_confirmation %>
  <%= f.submit "Sign Up" %>
<% end %>

app/views/users/new.html.erb
<h1>Sign Up</h1>

<%= render 'form' %>